# -*- coding: utf-8 -*-
"""face_data_label_compression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17pnxGkEz7ISUKy_HpPfI-SKJ50-N_m57
"""

import numpy as np

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/face-segmentation/one_hot_labels.npy"

labels = np.load(path)

labels = labels.astype(dtype=np.bool_)

np.save("/content/drive/MyDrive/face-segmentation/one_hot_labels_compressed.npy", labels)